settings:
  verbose: 0 # 0: minimal, 1: basic 2: extended
  global_random_seed: 42

pose_retargeting:
  data_base_path: "data/" 
  source_keypoints_file_suffix: "__KP3D.csv"
  target_keypoints_file_suffix: "__AL.csv"
  source_num_keypoints: 33
  target_num_keypoints: 54
  
  # Movement Filtering:
  # Provide a list of exact movement identifiers as found in the filenames.
  # The code will extract the part of the filename like "F-JUMP", "A-POSE", "F_J-JACKS"
  # movement_filter: ["F-JUMP"]                 # Only standard jumps
  # movement_filter: ["F-JUMP", "F_T-JUMP"]     # Standard jumps and T-jumps
  # movement_filter: ["A-POSE", "F-GAIT", "F-RUNNING"]
  # movement_filter: []                         # Load all movements
  movement_filter: ["GAIT"] 
  
  # Subject-based train/test split
  # Option 1: Ratio (subjects will be randomly split)
  # train_subject_ratio: 0.8 
  # Option 2: Explicit lists 
  train_subjects: ["TDB_001_F", "TDB_002_F", "TDB_003_M", "TDB_005_F", "TDB_006_M", "TDB_007_M", "TDB_008_M", "TDB_009_M", "TDB_010_F", "TDB_012_M", "TDB_013_M", "TDB_014_M", "TDB_015_M", "TDB_016_M", "TDB_017_F", "TDB_018_M", "TDB_019_M", "TDB_020_F", "TDB_021_M", "TDB_022_M", "TDB_023_M", "TDB_024_F", "TDB_025_F", "TDB_026_M", "TDB_027_F", "TDB_029_F", "TDB_030_M", "TDB_031_F", "TDB_033_F", "TDB_034_M", "TDB_036_F", "TDB_039_F", "TDB_040_F", "TDB_043_F", "TDB_044_F", "TDB_045_F", "TDB_046_F", "TDB_047_F", "TDB_048_F", "TDB_062_F", "TDB_063_F", "TDB_064_F", "TDB_065_M", "TDB_066_F", "TDB_067_F", "TDB_068_F", "TDB_069_M", "TDB_070_M", "TDB_050_F", "TDB_051_M", "TDB_052_M", "TDB_054_F", "TDB_056_M", "TDB_057_M", "TDB_058_M", "TDB_059_M", "TDB_060_M"]
  test_subjects: ["TDB_004_F", "TDB_011_M", "TDB_028_M", "TDB_032_F", "TDB_035_F", "TDB_037_M", "TDB_038_M", "TDB_041_F", "TDB_042_F", "TDB_049_F", "TDB_053_M", "TDB_055_M", "TDB_061_M", "TDB_071_F"]

  preprocessing:
    normalize_by_height: true  
    subject_characteristics_file: "SUBJECTS_CHARACTERISTICS.csv" 

genome_definition:
  C1_init_bounds: [0, 1]  # For correspondence matrix
  S_init_bounds: [0.5, 1.5] # For scaling factors
  B_init_bounds: [-0.2, 0.2] # For bias vectors

nsga3_optimizer:
  population_size: 10 # Start small
  num_generations: 5 # Start small
  crossover_prob: 0.9
  crossover_eta: 15 # For SBX
  mutation_prob: 0.1 # Per-variable mutation probability
  mutation_eta: 20  # For Polynomial Mutation

  # Weights for objectives (not used by NSGA-III directly, but for final selection)
  objective_weights:
    accuracy: 1.0
    temporal_consistency: 0.5
    # anatomical_plausibility: 0.2 # For future ?

bayesian_optimizer_settings:
  run_bayesian_opt: true
  max_evals_bo: 3         # Number of Hyperopt evaluations
  training_data_subset_ratio_bo: 0.2 # Use 20% of training data

  search_space:
    population_size: {type: "quniform", low: 30, high: 120, q: 1}
    crossover_prob: {type: "uniform", low: 0.7, high: 0.99}
    crossover_eta: {type: "quniform", low: 5, high: 30, q: 1}
    mutation_prob: {type: "uniform", low: 0.005, high: 0.15}
    mutation_eta: {type: "quniform", low: 10, high: 40, q: 1}

  base_nsga3_config_for_bo_eval:
    num_generations: 8